# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/active_storage_base64/all/active_storage_base64.rbi
#
# active_storage_base64-1.1.0

module ActiveStorageSupport
end
module ActiveStorageSupport::SupportForBase64
  extend ActiveSupport::Concern
end
module ActiveStorageSupport::SupportForBase64::ClassMethods
  def has_many_base64_attached(name, dependent: nil); end
  def has_one_base64_attached(name, dependent: nil); end
end
class ActiveStorageSupport::Base64One < ActiveStorage::Attached::One
  def attach(attachable); end
  def self.from_base64(attachable); end
end
class ActiveStorageSupport::Base64Many < ActiveStorage::Attached::Many
  def attach(*attachables); end
  def self.from_base64(attachables); end
end
module ActiveStorageSupport::Base64Attach
  def attachment_from_data(attachment); end
  def content_type(headers); end
  def fill_attachment_data(attachment, base64_data); end
  def self.attachment_from_data(attachment); end
  def self.content_type(headers); end
  def self.fill_attachment_data(attachment, base64_data); end
end
