version: "3.6"

x-rails: &rails
  image: progress-test-backend
  volumes:
    - .:/app:delegated
    - gems:/home/progress-test-backend:delegated
  environment:
    - RAILS_ENV=production
    - DISABLE_SPRING=1
    - DATABASE_URL=postgres://postgres:postgres@db:5432
    - SECRET_KEY_BASE=
    - MAILER_HOST_URL_REFERENCE=
    - GMAIL_USERNAME=
    - GMAIL_PASSWORD=

services:
  web:
    <<: *rails
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: progress-test-backend
    command: >
      sh -c '
        bundle check || bundle install &&
        rm -f tmp/pids/server.pid &&
        rails s -b 0.0.0.0'
    ports:
      - "3000:3000"

volumes:
  gems:
