# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_34; end
module ::Anonymous_Delegator_8; end
module ::FilterEncryptedAttributes; end
module ::ResponseError; end
module QuestionPolicy::Scope; end
